services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:password@db:5432/postgres"
    volumes:
      - ./api:/app

  streamlit:
      build:
        context: ./app
        dockerfile: Dockerfile
      ports:
        - "8501:8501"
      env_file:
        - ./app/.env
      volumes:
        - ./app:/app
      environment:
        - WEAVIATE_HOST=weaviate
        - WEAVIATE_PORT=8079
      depends_on:
        - weaviate
      restart: "on-failure"
  weaviate:
    env_file:
        - .env
    image: semitechnologies/weaviate:latest      
    command:
      - --host
      - 0.0.0.0
      - --port
      - '${WEAVIATE_PORT}'
      - --scheme
      - http
    ports:
      - '${WEAVIATE_PORT}:${WEAVIATE_PORT}'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: "on-failure"
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
volumes:
  weaviate_data: